def hometo2nabიji():
      print('გამოვედი სახლიდან')
      print('შევუხვუიე მარჯვნივ')
      print('წავედი წინ')
      print('შევუხვიე მარჯვნივ')
      print('გადავჭერი ხიდი')
      print('გავუხვიე მარცხნივ')
      print('წავედი წინ')
      print('შევუხვიე მარჯვნივ')
      print('წავედი წინ')
      print('შევუხვიე მარჯვნივ')
      print('წავედი წინ')
      print('შევუხვიე მარცხნივ')
      print('შევედი მაღაზიაში')

hometo2nabიji()
hometo2nabიji()
hometo2nabიji()
