print("my familiy members....")
print("luka chakhvashvili")
print("nino korkotashvili")
print("zura chaxvashvili")
print("gurami chaxvashvili")
print("saba chaxvashvili")
print("cira korkotashvili")
print("tamo churchadze")
print("tamriko varazanashvili")
